"""Generate manuscript figures and appendix tables from prepared results.

Figures 1 and 2 were not generated by Python in the submitted manuscript:

- Figure 1 was prepared in GIS software.
- Figure 2 was drawn in PowerPoint.

The functions below cover the Python-generated result figures and tables.
Revision-specific Tables S5-S7 are generated by scripts 07-09.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Mapping, Sequence

import numpy as np
import pandas as pd


DEFAULT_SPECIES_COLS = (
    "polychaeta_avg_final",
    "bivalvia_avg_final",
    "sipuncula_avg_final",
)


MANUSCRIPT_OUTPUT_CODE_INDEX = {
    "Figure 1": "external_figure_notes",
    "Figure 2": "external_figure_notes",
    "Figure 3": "plot_figure_3_sliding_interval_biomass",
    "Figure 4": [
        "plot_figure_4_aice_early_late_maps",
        "plot_figure_4_ice_adjusted_biomass_maps",
        "summarize_figure_4_ice_accessibility",
        "plot_figure_4_accessibility_timeseries",
    ],
    "Figure 5": [
        "plot_figure_5_upper_min_area_curves",
        "plot_figure_5_lower_ship_curves",
    ],
    "Figure 6": [
        "plot_figure_6_ship_exposure_maps",
        "plot_figure_6_ice_adjusted_biomass_maps",
        "plot_figure_6_stdi_violin_distribution",
    ],
    "Table 1": [
        "scripts/01_prepare_benthic_surfaces.py::compute_total_biomass_timeseries",
        "scripts/02_build_ice_accessibility.py::calculate_single_beta_fraction",
        "scripts/04_run_capacity_optimization.py::compute_area_inflation_decomposition",
        "scripts/04_run_capacity_optimization.py::compute_exact_ship_ceilings",
    ],
    "Table 2": "scripts/09_ice_internal_parameter_optimization.py::main",
    "Figure S1": "plot_figure_s1_baseline_spatial_efficiency",
    "Figure S2": "plot_figure_s2_prey_biomass_gini",
    "Figure S3": "scripts/05_temperature_auxiliary_analysis.py::plot_figure_s3_dbo1_temperature_biomass",
    "Figure S4": "scripts/05_temperature_auxiliary_analysis.py::plot_figure_s4_dbo4_temperature_biomass",
    "Figure S5": "plot_figure_s5_annual_ship_traffic_intensity",
    "Figure S6": "plot_figure_s6_ice_sensitivity",
    "Figure S7": "plot_figure_s7_dbo1_ice_ship_sensitivity_matrix",
    "Figure S8": "plot_figure_s8_dbo4_ice_ship_sensitivity_matrix",
    "Figure S9": "scripts/05_temperature_auxiliary_analysis.py::plot_figure_s9_stratification_proxy",
    "Table S1": "build_table_s1_ice_sensitivity",
    "Table S2": "scripts/04_run_capacity_optimization.py::build_table_s2_shipping_accessibility_loss",
    "Table S3": "scripts/03_build_ship_stdi.py::build_table_s3_ship_traffic_statistics",
    "Table S4": "scripts/05_temperature_auxiliary_analysis.py::build_table_s4_temperature_stratification_stats",
    "Table S5": "scripts/08_ice_internal_parameter_surfaces.py::SCENARIOS",
    "Table S6": "scripts/09_ice_internal_parameter_optimization.py::main",
    "Table S7": "scripts/07_kriging_leave_one_grid_cell_out.py::build_table_s7_summary",
}


def external_figure_notes() -> dict[str, str]:
    """Return notes for manuscript figures not generated by Python."""

    return {
        "Figure 1": "Generated in GIS software; not reproduced by the Python analysis code.",
        "Figure 2": "Drawn in PowerPoint; not reproduced by the Python analysis code.",
    }


def plot_biomass_timeseries_two_panel(
    dbo1_stats: pd.DataFrame,
    dbo4_stats: pd.DataFrame,
    savepath: str | Path | None = None,
):
    """Main-text Figure 3: bootstrap total benthic biomass time series."""

    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 2, figsize=(10, 4.4), sharey=False)
    configs = [
        (axes[0], dbo1_stats, "DBO1", "#1f78b4", "#a6cee3", "o"),
        (axes[1], dbo4_stats, "DBO4", "#33a02c", "#b2df8a", "s"),
    ]
    for ax, stats, label, line_color, band_color, marker in configs:
        ax.fill_between(
            stats["mid_year"],
            stats["lower_95"],
            stats["upper_95"],
            color=band_color,
            alpha=0.35,
            linewidth=0,
        )
        ax.plot(
            stats["mid_year"],
            stats["mean_total"],
            color=line_color,
            marker=marker,
            linewidth=2.2,
            markersize=4,
            label=label,
        )
        ax.set_xlabel("Sliding-interval mid-year")
        ax.set_ylabel("Total benthic prey biomass")
        ax.grid(alpha=0.25, linestyle="--")
        ax.legend(frameon=False)
    plt.tight_layout()
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight", pad_inches=0.02)
    return fig, axes


def plot_figure_3_sliding_interval_biomass(
    dbo1_stats: pd.DataFrame,
    dbo4_stats: pd.DataFrame,
    savepath: str | Path | None = None,
):
    """Manuscript Figure 3: sliding-interval prey biomass summaries."""

    return plot_biomass_timeseries_two_panel(dbo1_stats, dbo4_stats, savepath=savepath)


def gini(values: Sequence[float]) -> float:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    arr = arr[arr >= 0]
    if arr.size == 0:
        return float("nan")
    if np.all(arr == 0):
        return 0.0
    arr_sorted = np.sort(arr)
    n = arr_sorted.size
    cumulative = np.cumsum(arr_sorted)
    return float((n + 1 - 2 * np.sum(cumulative) / cumulative[-1]) / n)


def df_to_grid(df: pd.DataFrame, value_col: str, x_col: str = "grid_x", y_col: str = "grid_y") -> np.ndarray:
    """Convert long grid-cell table to 2D array."""

    return (
        df.pivot(index=y_col, columns=x_col, values=value_col)
        .sort_index(axis=0)
        .sort_index(axis=1)
        .values
    )


def ice_df_to_grid(df: pd.DataFrame, value_col: str = "A_mean") -> np.ndarray:
    return (
        df.pivot(index="y_idx", columns="x_idx", values=value_col)
        .sort_index(axis=0)
        .sort_index(axis=1)
        .values
    )


def window_mid_year(label: str) -> float:
    start, end = map(int, label.split("_"))
    return 0.5 * (start + end)


def get_early_late_windows(surface_dict: Mapping[str | tuple[int, int], pd.DataFrame]) -> tuple[object, object]:
    """Return first and last window keys by mid-year."""

    def key_mid(key) -> float:
        if isinstance(key, tuple):
            return 0.5 * (key[0] + key[1])
        return window_mid_year(str(key))

    keys = sorted(surface_dict, key=key_mid)
    return keys[0], keys[-1]


def plot_aice_early_late_site(
    ice_surfaces_dict: Mapping[str | tuple[int, int], pd.DataFrame],
    site_name: str,
    savepath: str | Path | None = None,
    vmin: float | None = None,
    vmax: float | None = None,
):
    """Main-text Figure 4 panel: early/late A_ice maps for one site."""

    import matplotlib.pyplot as plt

    early, late = get_early_late_windows(ice_surfaces_dict)
    fig, axes = plt.subplots(1, 2, figsize=(8, 4), constrained_layout=True)
    for ax, key, label in zip(axes, [early, late], ["early", "late"]):
        grid = ice_df_to_grid(ice_surfaces_dict[key], "A_mean")
        im = ax.imshow(grid, origin="lower", cmap="viridis", vmin=vmin, vmax=vmax)
        ax.set_title(f"{site_name} {label}")
        ax.set_xticks([])
        ax.set_yticks([])
    fig.colorbar(im, ax=axes, shrink=0.8, label="A_ice")
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight", pad_inches=0.02)
    return fig, axes


def plot_figure_4_aice_early_late_maps(
    ice_surfaces_dict: Mapping[str | tuple[int, int], pd.DataFrame],
    site_name: str,
    savepath: str | Path | None = None,
    vmin: float | None = None,
    vmax: float | None = None,
):
    """Manuscript Figure 4: early/late ice-accessibility (A_ice) maps."""

    return plot_aice_early_late_site(
        ice_surfaces_dict=ice_surfaces_dict,
        site_name=site_name,
        savepath=savepath,
        vmin=vmin,
        vmax=vmax,
    )


def plot_figure_4_ice_adjusted_biomass_maps(
    beta_surfaces_dict: Mapping[str, pd.DataFrame],
    site_name: str,
    windows_to_plot: Sequence[str],
    value_col: str = "total_biomass_beta",
    savepath: str | Path | None = None,
    cmap: str = "magma",
):
    """Manuscript Figure 4: ice-adjusted prey biomass maps for selected windows."""

    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, len(windows_to_plot), figsize=(4.2 * len(windows_to_plot), 4), constrained_layout=True)
    if len(windows_to_plot) == 1:
        axes = [axes]

    values = [
        df_to_grid(beta_surfaces_dict[window], value_col)
        for window in windows_to_plot
        if window in beta_surfaces_dict
    ]
    if not values:
        raise KeyError("None of the requested windows are present in beta_surfaces_dict")
    vmax = max(float(np.nanmax(grid)) for grid in values)

    image = None
    for ax, window in zip(axes, windows_to_plot):
        if window not in beta_surfaces_dict:
            ax.set_axis_off()
            ax.set_title(f"{site_name} {window} missing")
            continue
        image = ax.imshow(df_to_grid(beta_surfaces_dict[window], value_col), origin="lower", cmap=cmap, vmin=0, vmax=vmax)
        ax.set_title(f"{site_name} {window.replace('_', '-')}")
        ax.set_xticks([])
        ax.set_yticks([])
    if image is not None:
        fig.colorbar(image, ax=axes, shrink=0.8, label="Ice-adjusted prey biomass")
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight", pad_inches=0.02)
    return fig, axes


def summarize_ice_for_site(
    ice_surfaces_dict: Mapping[str | tuple[int, int], pd.DataFrame],
    site_name: str,
) -> pd.DataFrame:
    """Summarize mean A_ice and Gini(A_ice) across windows."""

    rows = []
    for key, df in ice_surfaces_dict.items():
        label = f"{key[0]}_{key[1]}" if isinstance(key, tuple) else str(key)
        rows.append(
            {
                "site": site_name,
                "window": label,
                "mid_year": window_mid_year(label),
                "mean_A": float(df["A_mean"].mean()),
                "gini_A": gini(df["A_mean"]),
            }
        )
    return pd.DataFrame(rows).sort_values("mid_year").reset_index(drop=True)


def summarize_figure_4_ice_accessibility(
    ice_surfaces_dict: Mapping[str | tuple[int, int], pd.DataFrame],
    site_name: str,
) -> pd.DataFrame:
    """Manuscript Figure 4: mean A_ice and Gini(A_ice) time-series source data."""

    return summarize_ice_for_site(ice_surfaces_dict, site_name=site_name)


def plot_ice_accessibility_timeseries_two_sites(
    summary_dbo1: pd.DataFrame,
    summary_dbo4: pd.DataFrame,
    value_col: str = "mean_A",
    ylabel: str = "Mean ice accessibility",
    savepath: str | Path | None = None,
):
    """Main-text Figure 4 time-series panels for A_ice or Gini(A_ice)."""

    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(summary_dbo1["mid_year"], summary_dbo1[value_col], color="#1f78b4", marker="o", label="DBO1")
    ax.plot(summary_dbo4["mid_year"], summary_dbo4[value_col], color="#33a02c", marker="s", label="DBO4")
    ax.set_xlabel("Sliding-interval mid-year")
    ax.set_ylabel(ylabel)
    ax.grid(alpha=0.3, linestyle="--")
    ax.legend(frameon=False)
    plt.tight_layout()
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight", pad_inches=0.02)
    return fig, ax


def plot_figure_4_accessibility_timeseries(
    summary_dbo1: pd.DataFrame,
    summary_dbo4: pd.DataFrame,
    value_col: str,
    ylabel: str,
    savepath: str | Path | None = None,
):
    """Manuscript Figure 4: mean A_ice or Gini(A_ice) time-series panel."""

    return plot_ice_accessibility_timeseries_two_sites(
        summary_dbo1=summary_dbo1,
        summary_dbo4=summary_dbo4,
        value_col=value_col,
        ylabel=ylabel,
        savepath=savepath,
    )


def extract_curve(curve_list: Sequence[Mapping[str, object]]) -> tuple[np.ndarray, np.ndarray]:
    """Extract feasible threshold and area-fraction arrays from curve records."""

    pairs = []
    for row in curve_list:
        if str(row.get("feasible", True)) == "False":
            continue
        area = row.get("area_fraction")
        if area is None:
            continue
        area_float = float(area)
        if np.isfinite(area_float):
            pairs.append((float(row["threshold"]), area_float))
    if not pairs:
        return np.array([]), np.array([])
    pairs = sorted(pairs)
    return np.array([p[0] for p in pairs]), np.array([p[1] for p in pairs])


def get_curve_robust(df_all: pd.DataFrame, site: str, beta: float, window: str) -> tuple[np.ndarray, np.ndarray]:
    """Extract ice-only curve arrays from long-form curve table."""

    mask = (
        (df_all["Site"] == site)
        & np.isclose(df_all["Beta"], beta)
        & (df_all["Window"] == window)
    )
    subset = df_all[mask].copy()
    if subset.empty:
        return np.array([]), np.array([])
    if subset["Feasible"].dtype == object:
        subset["Feasible"] = subset["Feasible"].astype(str) == "True"
    valid = subset[subset["Feasible"]].sort_values("Threshold_Pct")
    return valid["Threshold_Pct"].values, valid["Min_Area_Ratio"].values


def get_ship_ice_robust(
    df_all: pd.DataFrame,
    site: str,
    beta: float,
    alpha: float,
    window: str,
) -> tuple[np.ndarray, np.ndarray]:
    """Extract ice+ship curve arrays from long-form curve table."""

    mask = (
        (df_all["Site"] == site)
        & np.isclose(df_all["Beta"], beta)
        & np.isclose(df_all["Alpha"], alpha)
        & (df_all["Window"] == window)
    )
    subset = df_all[mask].copy()
    if subset.empty:
        return np.array([]), np.array([])
    if subset["Feasible"].dtype == object:
        subset["Feasible"] = subset["Feasible"].astype(str) == "True"
    valid = subset[subset["Feasible"]].sort_values("Threshold_Pct")
    return valid["Threshold_Pct"].values, valid["Min_Area_Ratio"].values


def get_pure_robust(pure_dict: Mapping[str, Sequence[Mapping[str, object]]], window: str) -> tuple[np.ndarray, np.ndarray]:
    if window not in pure_dict:
        return np.array([]), np.array([])
    return extract_curve(pure_dict[window])


def plot_main_text_final(
    df_curves_all: pd.DataFrame,
    pure_curves_dict: Mapping[str, Sequence[Mapping[str, object]]],
    site_name: str,
    windows_to_plot: Sequence[str],
    beta_main: float = 0.5,
    savepath: str | Path | None = None,
):
    """Manuscript Figure 5 upper panels: pure vs ice-adjusted curves."""

    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, len(windows_to_plot), figsize=(5 * len(windows_to_plot), 5), sharey=True)
    if len(windows_to_plot) == 1:
        axes = [axes]
    for ax, window in zip(axes, windows_to_plot):
        t_pure, a_pure = get_pure_robust(pure_curves_dict, window)
        t_ice, a_ice = get_curve_robust(df_curves_all, site_name, beta_main, window)
        if len(t_pure):
            ax.plot(t_pure * 100, a_pure * 100, color="black", marker="o", label="Pure biomass")
        if len(t_ice):
            ax.plot(t_ice * 100, a_ice * 100, color="#1f77b4", marker="s", linestyle="--", label=f"Ice-adjusted (beta={beta_main})")
        ax.set_title(window.replace("_", "-"))
        ax.set_xlabel("Target biomass threshold (%)")
        ax.set_xlim(0, 105)
        ax.set_ylim(0, 105)
        ax.grid(True, linestyle=":", alpha=0.6)
        if ax == axes[0]:
            ax.set_ylabel("Minimum area required (% of site)")
            ax.legend(frameon=True, framealpha=0.9)
    plt.tight_layout()
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight")
    return fig, axes


def plot_figure_5_upper_min_area_curves(
    df_curves_all: pd.DataFrame,
    pure_curves_dict: Mapping[str, Sequence[Mapping[str, object]]],
    site_name: str,
    windows_to_plot: Sequence[str],
    beta_main: float = 0.5,
    savepath: str | Path | None = None,
):
    """Manuscript Figure 5 upper panels: pure vs ice-adjusted minimum-area curves."""

    return plot_main_text_final(
        df_curves_all=df_curves_all,
        pure_curves_dict=pure_curves_dict,
        site_name=site_name,
        windows_to_plot=windows_to_plot,
        beta_main=beta_main,
        savepath=savepath,
    )


def plot_main_text_ship_precise_fixed(
    df_ice_only: pd.DataFrame,
    df_ship_ice: pd.DataFrame,
    pure_dict: Mapping[str, Sequence[Mapping[str, object]]],
    df_exact_ice_ceilings: pd.DataFrame,
    df_exact_ship_ceilings: pd.DataFrame,
    site_name: str,
    ship_windows: Sequence[str],
    beta_main: float = 0.5,
    alpha_main: float = 0.5,
    savepath: str | Path | None = None,
):
    """Manuscript Figure 5 lower panels: pure, ice-only, and ice+ship curves."""

    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, len(ship_windows), figsize=(5 * len(ship_windows), 5), sharey=True)
    if len(ship_windows) == 1:
        axes = [axes]
    for ax, window in zip(axes, ship_windows):
        t_pure, a_pure = get_pure_robust(pure_dict, window)
        t_ice, a_ice = get_ship_ice_robust(df_ice_only, site_name, beta_main, 0.0, window)
        t_ship, a_ship = get_ship_ice_robust(df_ship_ice, site_name, beta_main, alpha_main, window)

        row_ice = df_exact_ice_ceilings[
            (df_exact_ice_ceilings["Site"] == site_name)
            & (df_exact_ice_ceilings["Window"] == window)
            & np.isclose(df_exact_ice_ceilings["Beta"], beta_main)
        ]
        row_ship = df_exact_ship_ceilings[
            (df_exact_ship_ceilings["Site"] == site_name)
            & (df_exact_ship_ceilings["Window"] == window)
            & np.isclose(df_exact_ship_ceilings["Beta"], beta_main)
            & np.isclose(df_exact_ship_ceilings["Alpha"], alpha_main)
        ]
        ice_ceil = row_ice["Exact_Ceiling"].values[0] * 100 if not row_ice.empty else np.nan
        ship_ceil = row_ship["Exact_Ceiling"].values[0] * 100 if not row_ship.empty else np.nan

        if len(t_pure):
            ax.plot(t_pure * 100, a_pure * 100, color="black", marker="o", label="Pure biomass")
        if len(t_ice):
            ax.plot(t_ice * 100, a_ice * 100, color="#1f77b4", marker="s", linestyle="--", label=f"Ice-adjusted (beta={beta_main})")
        if len(t_ship):
            ax.plot(t_ship * 100, a_ship * 100, color="#d62728", marker="^", linestyle="-.", label=f"Ice + ship (alpha={alpha_main})")
        if np.isfinite(ice_ceil) and ice_ceil < 99:
            ax.axvline(ice_ceil, color="#1f77b4", linestyle=":", linewidth=1.5)
        if np.isfinite(ship_ceil) and ship_ceil < 99:
            ax.axvline(ship_ceil, color="#d62728", linewidth=1.5)
            ax.axvspan(ship_ceil, 105, color="#d62728", alpha=0.1)

        ax.set_title(window.replace("_", "-"))
        ax.set_xlabel("Target biomass threshold (%)")
        ax.set_xlim(0, 102)
        ax.set_ylim(0, 105)
        ax.grid(True, linestyle=":", alpha=0.6)
        if ax == axes[0]:
            ax.set_ylabel("Minimum area required (% of site)")
            ax.legend(frameon=True, framealpha=0.9)
    plt.tight_layout()
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight")
    return fig, axes


def plot_figure_5_lower_ship_curves(
    df_ice_only: pd.DataFrame,
    df_ship_ice: pd.DataFrame,
    pure_dict: Mapping[str, Sequence[Mapping[str, object]]],
    df_exact_ice_ceilings: pd.DataFrame,
    df_exact_ship_ceilings: pd.DataFrame,
    site_name: str,
    ship_windows: Sequence[str],
    beta_main: float = 0.5,
    alpha_main: float = 0.5,
    savepath: str | Path | None = None,
):
    """Manuscript Figure 5 lower panels: pure, ice-only, and ice+ship curves."""

    return plot_main_text_ship_precise_fixed(
        df_ice_only=df_ice_only,
        df_ship_ice=df_ship_ice,
        pure_dict=pure_dict,
        df_exact_ice_ceilings=df_exact_ice_ceilings,
        df_exact_ship_ceilings=df_exact_ship_ceilings,
        site_name=site_name,
        ship_windows=ship_windows,
        beta_main=beta_main,
        alpha_main=alpha_main,
        savepath=savepath,
    )


def plot_figure_6_ship_exposure_maps(
    stdi_dict: Mapping[str, pd.DataFrame],
    site_name: str,
    windows_to_plot: Sequence[str],
    value_col: str = "STDI_window_mean",
    savepath: str | Path | None = None,
    cmap: str = "viridis",
):
    """Manuscript Figure 6: ship-exposure/STDI maps for ship-supported windows."""

    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, len(windows_to_plot), figsize=(4.2 * len(windows_to_plot), 4), constrained_layout=True)
    if len(windows_to_plot) == 1:
        axes = [axes]

    values = [df_to_grid(stdi_dict[window], value_col) for window in windows_to_plot if window in stdi_dict]
    if not values:
        raise KeyError("None of the requested windows are present in stdi_dict")
    vmax = max(float(np.nanmax(grid)) for grid in values)

    image = None
    for ax, window in zip(axes, windows_to_plot):
        if window not in stdi_dict:
            ax.set_axis_off()
            ax.set_title(f"{site_name} {window} missing")
            continue
        image = ax.imshow(df_to_grid(stdi_dict[window], value_col), origin="lower", cmap=cmap, vmin=0, vmax=vmax)
        ax.set_title(f"{site_name} {window.replace('_', '-')}")
        ax.set_xticks([])
        ax.set_yticks([])
    if image is not None:
        fig.colorbar(image, ax=axes, shrink=0.8, label="STDI")
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight", pad_inches=0.02)
    return fig, axes


def plot_figure_6_ice_adjusted_biomass_maps(
    beta_surfaces_dict: Mapping[str, pd.DataFrame],
    site_name: str,
    ship_windows: Sequence[str],
    value_col: str = "total_biomass_beta",
    savepath: str | Path | None = None,
):
    """Manuscript Figure 6: ice-adjusted prey biomass maps for ship windows."""

    return plot_figure_4_ice_adjusted_biomass_maps(
        beta_surfaces_dict=beta_surfaces_dict,
        site_name=site_name,
        windows_to_plot=ship_windows,
        value_col=value_col,
        savepath=savepath,
    )


def build_figure_6_stdi_long_df(
    stdi_by_site_window: Mapping[str, Mapping[str, pd.DataFrame]],
    value_col: str = "STDI_window_mean",
) -> pd.DataFrame:
    """Manuscript Figure 6: long-form source table for STDI distribution violin plots."""

    rows = []
    for site, window_dict in stdi_by_site_window.items():
        for window, df in window_dict.items():
            if value_col not in df.columns:
                raise KeyError(f"{site} {window} missing {value_col}")
            for value in df[value_col].dropna().values:
                rows.append({"Site": site, "Window": window, "STDI": float(value)})
    return pd.DataFrame(rows)


def plot_figure_6_stdi_violin_distribution(
    stdi_long_df: pd.DataFrame,
    savepath: str | Path | None = None,
):
    """Manuscript Figure 6: grid-cell STDI distribution violin panel."""

    import matplotlib.pyplot as plt
    import seaborn as sns

    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    sns.violinplot(
        data=stdi_long_df,
        x="Site",
        y="STDI",
        hue="Window",
        inner=None,
        cut=0,
        linewidth=0.8,
        ax=ax,
    )
    sns.boxplot(
        data=stdi_long_df,
        x="Site",
        y="STDI",
        hue="Window",
        width=0.22,
        showcaps=True,
        boxprops={"facecolor": "white", "zorder": 3},
        showfliers=False,
        whiskerprops={"linewidth": 0.8},
        ax=ax,
    )
    handles, labels = ax.get_legend_handles_labels()
    if handles:
        n = len(handles) // 2 if len(handles) > 2 else len(handles)
        ax.legend(handles[:n], labels[:n], frameon=False, title="")
    ax.set_ylabel("Ship Traffic Disturbance Index")
    ax.set_xlabel("")
    ax.grid(axis="y", alpha=0.3, linestyle=":")
    plt.tight_layout()
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight", pad_inches=0.02)
    return fig, ax


def plot_si_6panels(
    site: str,
    ship_windows: Sequence[str],
    pure_dict: Mapping[str, Sequence[Mapping[str, object]]],
    df_ice_only: pd.DataFrame,
    df_cross: pd.DataFrame,
    savepath: str | Path | None = None,
):
    """Appendix S7/S8: beta-by-window ice+ship sensitivity matrix."""

    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(3, 2, figsize=(10, 12), sharex=True, sharey=True)
    betas = [0.3, 0.5, 0.8]
    alphas = [0.3, 0.5, 0.8]
    colors = {0.3: "#ff9896", 0.5: "#d62728", 0.8: "#8c564b"}
    panel_letters = ["(a)", "(b)", "(c)", "(d)", "(e)", "(f)"]

    for row_idx, beta in enumerate(betas):
        for col_idx, window in enumerate(ship_windows):
            ax = axes[row_idx, col_idx]
            ax.text(0.04, 0.96, panel_letters[row_idx * 2 + col_idx], transform=ax.transAxes, fontweight="bold", va="top")
            t_pure, a_pure = get_pure_robust(pure_dict, window)
            if len(t_pure):
                ax.plot(t_pure * 100, a_pure * 100, color="black", lw=2.0, label="Pure biomass")
            t_ice, a_ice = get_ship_ice_robust(df_ice_only, site, beta, 0.0, window)
            if len(t_ice):
                ax.plot(t_ice * 100, a_ice * 100, color="#1f77b4", linestyle="--", lw=2.0, label="Ice-only")
            for alpha in alphas:
                t_ship, a_ship = get_ship_ice_robust(df_cross, site, beta, alpha, window)
                if len(t_ship):
                    ax.plot(t_ship * 100, a_ship * 100, color=colors[alpha], linestyle="-.", lw=1.5, label=f"alpha={alpha}")
            ax.set_title(f"{window.replace('_', '-')}\nbeta={beta}" if row_idx == 0 else f"beta={beta}")
            ax.set_xlim(0, 105)
            ax.set_ylim(0, 105)
            ax.grid(True, linestyle=":", alpha=0.5)
            if col_idx == 0:
                ax.set_ylabel("Minimum area (% of site)")
            if row_idx == 2:
                ax.set_xlabel("Target biomass threshold (%)")
    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=5, bbox_to_anchor=(0.5, 0.97), frameon=False)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight", pad_inches=0.02)
    return fig, axes


def plot_figure_s1_baseline_spatial_efficiency(
    min_area_curves: Mapping[str, Sequence[Mapping[str, object]]],
    baseline_window: str,
    comparison_windows: Sequence[str],
    site_name: str,
    savepath: str | Path | None = None,
):
    """Appendix Figure S1: pure-biomass baseline spatial-efficiency differences."""

    import matplotlib.pyplot as plt

    baseline_thresholds, baseline_area = get_pure_robust(min_area_curves, baseline_window)
    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    for window in comparison_windows:
        thresholds, area = get_pure_robust(min_area_curves, window)
        if len(thresholds) == 0:
            continue
        common = sorted(set(np.round(baseline_thresholds, 8)) & set(np.round(thresholds, 8)))
        if not common:
            continue
        base_lookup = dict(zip(np.round(baseline_thresholds, 8), baseline_area))
        comp_lookup = dict(zip(np.round(thresholds, 8), area))
        diff = np.array([comp_lookup[t] - base_lookup[t] for t in common])
        ax.plot(np.array(common) * 100, diff * 100, marker="o", linewidth=2, label=f"{window.replace('_', '-')} - {baseline_window.replace('_', '-')}")
    ax.axhline(0, color="black", linewidth=1, linestyle="--")
    ax.set_xlabel("Prey biomass threshold (%)")
    ax.set_ylabel("Difference in minimum area required (% of site)")
    ax.set_title(f"{site_name}: baseline spatial efficiency")
    ax.grid(True, alpha=0.3)
    ax.legend(frameon=False)
    plt.tight_layout()
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight", pad_inches=0.02)
    return fig, ax


def plot_figure_s2_prey_biomass_gini(
    dbo1_gini_ts: pd.DataFrame,
    dbo4_gini_ts: pd.DataFrame,
    savepath: str | Path | None = None,
):
    """Appendix Figure S2: temporal variation in benthic prey-biomass Gini."""

    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(7.5, 4.0))
    ax.plot(dbo1_gini_ts["mid_year"], dbo1_gini_ts["gini"], color="#1f78b4", linewidth=2.2, marker="o", label="DBO1")
    ax.plot(dbo4_gini_ts["mid_year"], dbo4_gini_ts["gini"], color="#33a02c", linewidth=2.2, marker="s", label="DBO4")
    ax.set_xlabel("Sliding-interval mid-year")
    ax.set_ylabel("Gini index of benthic prey")
    ax.grid(alpha=0.3, linestyle="--")
    ax.legend(frameon=False)
    plt.tight_layout()
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight", pad_inches=0.02)
    return fig, ax


def plot_figure_s5_annual_ship_traffic_intensity(
    df_dbo1: pd.DataFrame,
    df_dbo4: pd.DataFrame,
    value_col: str = "total_STDI",
    savepath: str | Path | None = None,
):
    """Appendix Figure S5: annual ship-traffic intensity for DBO1 and DBO4."""

    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(7.5, 4.2))
    ax.plot(df_dbo1["year"], df_dbo1[value_col], color="#1f78b4", marker="o", linewidth=2, label="DBO1")
    ax.plot(df_dbo4["year"], df_dbo4[value_col], color="#33a02c", marker="s", linewidth=2, label="DBO4")
    ax.set_xlabel("Year")
    ax.set_ylabel(value_col.replace("_", " "))
    ax.grid(alpha=0.3, linestyle="--")
    ax.legend(frameon=False)
    plt.tight_layout()
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight", pad_inches=0.02)
    return fig, ax


def plot_figure_s6_ice_sensitivity(
    df_curves_all: pd.DataFrame,
    pure_curves_dict: Mapping[str, Sequence[Mapping[str, object]]],
    site_name: str,
    windows_to_plot: Sequence[str],
    savepath: str | Path | None = None,
):
    """Appendix Figure S6: sensitivity of minimum-area curves to beta values."""

    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, len(windows_to_plot), figsize=(5 * len(windows_to_plot), 5), sharey=True)
    if len(windows_to_plot) == 1:
        axes = [axes]
    styles = {
        0.3: {"color": "#2ca02c", "ls": "--", "marker": "^", "label": "beta=0.3"},
        0.5: {"color": "#1f77b4", "ls": "-.", "marker": "s", "label": "beta=0.5"},
        0.8: {"color": "#d62728", "ls": ":", "marker": "D", "label": "beta=0.8"},
    }
    for ax, window in zip(axes, windows_to_plot):
        t_pure, a_pure = get_pure_robust(pure_curves_dict, window)
        if len(t_pure):
            ax.plot(t_pure * 100, a_pure * 100, color="black", linewidth=2, marker="o", label="Pure biomass")
        for beta, style in styles.items():
            t_ice, a_ice = get_curve_robust(df_curves_all, site_name, beta, window)
            if len(t_ice):
                ax.plot(t_ice * 100, a_ice * 100, color=style["color"], linestyle=style["ls"], marker=style["marker"], label=style["label"])
        ax.set_title(f"{site_name}: {window.replace('_', '-')}")
        ax.set_xlabel("Target biomass threshold (%)")
        ax.set_xlim(0, 105)
        ax.set_ylim(0, 105)
        ax.grid(True, linestyle=":", alpha=0.5)
        if ax == axes[0]:
            ax.set_ylabel("Minimum area required (% of site)")
            ax.legend(frameon=True, framealpha=0.95)
    plt.tight_layout()
    if savepath is not None:
        plt.savefig(savepath, dpi=600, bbox_inches="tight")
    return fig, axes


def plot_figure_s7_dbo1_ice_ship_sensitivity_matrix(
    ship_windows: Sequence[str],
    pure_dict: Mapping[str, Sequence[Mapping[str, object]]],
    df_ice_only: pd.DataFrame,
    df_cross: pd.DataFrame,
    savepath: str | Path | None = None,
):
    """Appendix Figure S7: DBO1 beta-alpha ice+ship sensitivity matrix."""

    return plot_si_6panels("DBO1", ship_windows, pure_dict, df_ice_only, df_cross, savepath=savepath)


def plot_figure_s8_dbo4_ice_ship_sensitivity_matrix(
    ship_windows: Sequence[str],
    pure_dict: Mapping[str, Sequence[Mapping[str, object]]],
    df_ice_only: pd.DataFrame,
    df_cross: pd.DataFrame,
    savepath: str | Path | None = None,
):
    """Appendix Figure S8: DBO4 beta-alpha ice+ship sensitivity matrix."""

    return plot_si_6panels("DBO4", ship_windows, pure_dict, df_ice_only, df_cross, savepath=savepath)


def generate_full_ice_sensitivity_table(
    site: str,
    all_windows: Sequence[str],
    base_dir: str | Path,
    ice_dict: Mapping[str, pd.DataFrame],
    betas: Sequence[float] = (0.3, 0.5, 0.8),
    species_cols: Sequence[str] = DEFAULT_SPECIES_COLS,
) -> pd.DataFrame:
    """Appendix Table S1: biomass and attainable fraction for beta values."""

    rows = []
    for window in all_windows:
        path = Path(base_dir) / f"{site}_surfaces" / f"{site}_surface_{window}.csv"
        if not path.exists() or window not in ice_dict:
            continue
        df = pd.read_csv(path)
        pure_total = float(df[list(species_cols)].sum(axis=1).sum())
        merged = df.merge(
            ice_dict[window][["y_idx", "x_idx", "A_mean"]],
            left_on=["grid_y", "grid_x"],
            right_on=["y_idx", "x_idx"],
            how="left",
        )
        merged["A_mean"] = merged["A_mean"].fillna(0.0).clip(0.0, 1.0)
        for beta in betas:
            a_beta = 1.0 - beta * (1.0 - merged["A_mean"])
            adjusted = sum((merged[col] * a_beta).sum() for col in species_cols)
            rows.append(
                {
                    "Site": site,
                    "Time Interval": window.replace("_", "-"),
                    "Sensitivity (beta)": beta,
                    "Total biomass": round(pure_total, 1),
                    "Ice-adjusted biomass": round(float(adjusted), 1),
                    "Maximum attainable fraction (%)": round(100 * adjusted / pure_total, 1) if pure_total > 0 else np.nan,
                }
            )
    return pd.DataFrame(rows)


def build_table_s1_ice_sensitivity(
    site: str,
    all_windows: Sequence[str],
    base_dir: str | Path,
    ice_dict: Mapping[str, pd.DataFrame],
    betas: Sequence[float] = (0.3, 0.5, 0.8),
    species_cols: Sequence[str] = DEFAULT_SPECIES_COLS,
) -> pd.DataFrame:
    """Appendix Table S1: functional biomass and attainable fraction by beta."""

    return generate_full_ice_sensitivity_table(
        site=site,
        all_windows=all_windows,
        base_dir=base_dir,
        ice_dict=ice_dict,
        betas=betas,
        species_cols=species_cols,
    )


def create_publication_ready_station_table(input_csv: str | Path, output_excel: str | Path) -> pd.DataFrame:
    """Format station-level prey data as a supplementary station table."""

    df = pd.read_csv(input_csv)
    sp_cols = ["mean_gc_Polychaeta_1", "mean_gc_Bivalvia_1", "mean_gc_Sipuncula_1"]
    df["Total_gC_Biomass"] = df[sp_cols].sum(axis=1).round(2)
    df["Dominant_Fauna"] = (
        df[sp_cols]
        .idxmax(axis=1)
        .str.replace("mean_gc_", "", regex=False)
        .str.replace("_1", "", regex=False)
    )
    final = pd.DataFrame(
        {
            "Station (Grid Cell)": df["GridCellNme"],
            "Latitude": df["Latitude_Center"].round(4),
            "Longitude": df["Longitude_Center"].round(4),
            "Sampling Year": df["DataYear"],
            "Total Biomass (gC/m2)": df["Total_gC_Biomass"],
            "Dominant Faunal Type": df["Dominant_Fauna"],
        }
    ).sort_values(["Sampling Year", "Station (Grid Cell)"])
    final.to_excel(output_excel, index=False)
    return final


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--describe", action="store_true", help="print module purpose and exit")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    if args.describe:
        print("Generates Python-derived manuscript figures and appendix tables from prepared results.")
        for fig, note in external_figure_notes().items():
            print(f"{fig}: {note}")
        print("\nManuscript output code index:")
        for output, target in MANUSCRIPT_OUTPUT_CODE_INDEX.items():
            if isinstance(target, list):
                target_text = "; ".join(target)
            else:
                target_text = target
            print(f"  - {output}: {target_text}")
    else:
        print("Import this module and call the relevant plot_* or table-generation function.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
